show_res: true
camera:
  type: zed
  intrin:
    fx: 262.645874
    fy: 262.645874
    cx: 325.72876
    cy: 188.240692
    distortion_coeffs: [0, 0, 0, 0, 0, 0, 0, 0]
    distortion_model: 1 # 0: none, 1: opencv format, 2: for rs d455 only
  extrin:
    - [-0.0179711897, -0.0198142454,  0.999642193 , -0.0315812342]
    - [-0.999827445 ,  0.00504458416, -0.0178745314, -0.102936901 ]
    - [-0.00468860893,-0.999790847 , -0.0199014824, -0.0292825643]
    - [ 0.          ,  0.          ,  0.          ,  1.          ]
  pitch_compensation: 0.0 # in degree
  yaw_compensation: 0.0
  z_compensation: 0.0
detection_model:
  model_path: ./src/vision/model/best_orin_10.3.engine
  confidence_threshold: 0.2
use_depth: true
ball_pose_estimator:
  use_depth: false
  radius: 0.1109
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
human_like_pose_estimator:
  use_depth: false
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
  
